---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:${CP_VERSION}
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
    depends_on:
      - zookeeper
  schema-registry:
    image: confluentinc/cp-schema-registry:${CP_VERSION}
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - kafka
  ksqldb:
    image: confluentinc/ksqldb-server:0.9.0
    ports:
      - 8088:8088
    environment:
      KSQL_CONFIG_DIR: /etc/ksql
      KSQL_BOOTSTRAP_SERVERS: kafka:29092
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_QUERIES_FILE: /ksql/statement.ksql
#      KSQL_KSQL_CONNECT_WORKER_CONFIG: /connect/connect.properties
#      KSQL_CONNECT_GROUP_ID: ksql-connect-cluster
#      KSQL_CONNECT_BOOTSTRAP_SERVERS: kafka:29092
#      KSQL_CONNECT_REST_ADVERTISED_HOST_NAME: ksqldb
#      KSQL_CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
#      KSQL_CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      KSQL_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
#      KSQL_CONNECT_CONFIG_STORAGE_TOPIC: ksql-connect-configs
#      KSQL_CONNECT_OFFSET_STORAGE_TOPIC: ksql-connect-offsets
#      KSQL_CONNECT_STATUS_STORAGE_TOPIC: ksql-connect-statuses
#      KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
#      KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
#      KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
#      KSQL_CONNECT_PLUGIN_PATH: /usr/share/kafka/plugins
      KSQL_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KSQL_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
    volumes:
      - ./statement.ksql:/ksql/statement.ksql